# Generated by Django 5.1.3 on 2024-12-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='img',
            new_name='imgs',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='img',
            new_name='imgs',
        ),
        migrations.RemoveField(
            model_name='carousol',
            name='img',
        ),
        migrations.RemoveField(
            model_name='offerbanner',
            name='img',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='img',
        ),
        migrations.AddField(
            model_name='carousol',
            name='imgs',
            field=models.ImageField(blank=True, null=True, upload_to='Carousol_image'),
        ),
        migrations.AddField(
            model_name='offerbanner',
            name='imgs',
            field=models.ImageField(blank=True, null=True, upload_to='offerbanner/banner-image'),
        ),
        migrations.AddField(
            model_name='product',
            name='imgs',
            field=models.ImageField(blank=True, null=True, upload_to='product/product-image'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='imgs',
            field=models.ImageField(blank=True, null=True, upload_to='product/product/product-image'),
        ),
    ]
