# Generated by Django 5.1.3 on 2024-12-03 05:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_img_blog_imgs_rename_img_productcategory_imgs_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='imgs',
        ),
        migrations.RemoveField(
            model_name='carousol',
            name='imgs',
        ),
        migrations.RemoveField(
            model_name='offerbanner',
            name='imgs',
        ),
        migrations.RemoveField(
            model_name='product',
            name='imgs',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='imgs',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='imgs',
        ),
        migrations.AddField(
            model_name='blog',
            name='img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='blog-image'),
        ),
        migrations.AddField(
            model_name='carousol',
            name='img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Carousol_image'),
        ),
        migrations.AddField(
            model_name='offerbanner',
            name='img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='banner-image'),
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='product-image'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='categories-image'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='product-images'),
        ),
    ]
