# Generated by Django 5.1.3 on 2024-12-09 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_delete_student_remove_blog_imgs_remove_carousol_imgs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='colour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.colour'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.size'),
        ),
    ]
