# Generated by Django 5.1.3 on 2024-12-12 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_variation_colour_alter_variation_size'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variation',
            unique_together={('product', 'size', 'colour')},
        ),
    ]
