# Generated by Django 5.1.3 on 2024-12-18 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_free_delivery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
