# Generated by Django 5.1.3 on 2024-12-18 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_variation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
