# Generated by Django 5.1.3 on 2024-12-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_product_discount_price_remove_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parent_code',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
