# Generated by Django 5.1.3 on 2024-12-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_rename_color_variation_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_code',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
