# Generated by Django 5.1.3 on 2024-12-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_variation_variation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='quantity',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
