# Generated by Django 5.1.3 on 2024-12-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_variation_quantity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='product',
            name='parent_code',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
