# Generated by Django 5.1.3 on 2024-12-21 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_variation_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
