# Generated by Django 5.1.3 on 2024-12-24 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_brand_product_brand'),
        ('store', '0021_order_shipping'),
    ]

    operations = [
    ]
