# Generated by Django 5.1.3 on 2024-12-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_merge_0019_brand_product_brand_0021_order_shipping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
