# Generated by Django 5.1.3 on 2025-01-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_brand_options_alter_variation_variation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='used',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='variation',
            unique_together={('product', 'size', 'color')},
        ),
    ]
