# Generated by Django 5.1.3 on 2024-12-03 05:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_aboutus_img_aboutus_imgs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='imgs',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='about_us-image'),
        ),
    ]
