# Generated by Django 5.1.3 on 2024-12-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='order_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
