# Generated by Django 5.1.3 on 2024-12-21 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_shippingaddress_email_shippingaddress_order_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
    ]
