# Generated by Django 5.1.3 on 2024-12-03 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorprofile',
            old_name='image',
            new_name='imgs',
        ),
    ]
