# Generated by Django 5.1.3 on 2024-12-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_image_vendorprofile_imgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='imgs',
            field=models.ImageField(blank=True, null=True, upload_to='vendorpicture'),
        ),
    ]
