# Generated by Django 5.1.3 on 2024-12-03 05:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_vendorprofile_imgs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorprofile',
            name='imgs',
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='vendorpicture-image'),
        ),
    ]
